In [1]:
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error

In [2]:
# Load data
df = read_csv('D:\prediction\sleep_health.csv')

In [3]:
# Drop rows with missing values
df = df.dropna()

In [4]:
df

,gender,age,sleep_duration,sleep_quality,stress_lvl,bmi,heart_rate,daily_steps,sleep_disorder
0,1,27,6.1,6,6,2,77,4200,0
1,1,28,6.2,6,8,1,75,10000,0
2,1,28,6.2,6,8,1,75,10000,0
3,1,28,5.9,4,8,3,85,3000,1
4,1,28,5.9,4,8,3,85,3000,1
...,...,...,...,...,...,...,...,...,...
369,0,59,8.1,9,3,2,68,7000,1
370,0,59,8.0,9,3,2,68,7000,1
371,0,59,8.1,9,3,2,68,7000,1
372,0,59,8.1,9,3,2,68,7000,1
373,0,59,8.1,9,3,2,68,7000,1

In [5]:
# Select features and target
y = df['heart_rate']
X = df[['gender', 'age', 'sleep_duration', 'sleep_quality', 'stress_lvl', 'bmi', 'sleep_disorder', 'daily_steps']]

In [6]:
# Feature scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [7]:
# Splitting the data into a training set and a testing set (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.20, random_state=50)

In [8]:
from sklearn.ensemble import RandomForestRegressor

# Random Forest Regressor model
rf_model = RandomForestRegressor(random_state=42)

# Training the model on the training data
rf_model.fit(X_train, y_train)

# Making predictions on the test data
rf_y_pred = rf_model.predict(X_test)

# Calculating the Mean Absolute Error (MAE) for Random Forest
rf_mae = mean_absolute_error(y_test, rf_y_pred)
print(f"Random Forest Mean Absolute Error (MAE): {rf_mae:.3f}")

import pickle
with open('regression.pkl','wb') as files:
    pickle.dump(rf_model,files)

Random Forest Mean Absolute Error (MAE): 0.319